### PR TITLE
Reworked console terminal.

### PR DESCRIPTION
**Pull request by SaphireLattice**
Haven't really tested it, so obviously needs some testing.

### CODE REVIEW

**Comment by kevinramharak** [comment]
Stuff that could be added:
- `scrl` should scroll down when toggled on
- use of `window.localStorage` to remember the font-size
- some way of manualy scrolling up and down? And those should by default toggle `scrl` off

Looks good

**Comment by SaphireLattice** [comment]
- Sounds a bit annoying if you scrolled up to check something and toggled autoscroll. But makes sense. Guess that could be added.
- Perhaps? Not unlikely to be added right now, unless there's some save system in `mar.js`.
- Weird, that is actually in. You need to scroll over it. Unless you're on a touch-screen device I guess. Toggle could be added actually, been thinking of same thing.

**Comment by ChartreuseK** [comment]
Is there anything left preventing this from being merged? It'd be nice to have this more console like console. I presume there's a way of scrolling without having a scrollwheel now?

**Comment by simon987** [comment]
> Is there anything left preventing this from being merged? 

The frontend is being re-written. I will apply the modification when that will be done.

**Pull request closed without merging**
